//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CopyFiles.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CopyFiles.Properties.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Files Tool.
        /// </summary>
        internal static string str001 {
            get {
                return ResourceManager.GetString("str001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use from.
        /// </summary>
        internal static string str002 {
            get {
                return ResourceManager.GetString("str002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use to.
        /// </summary>
        internal static string str003 {
            get {
                return ResourceManager.GetString("str003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore if exists.
        /// </summary>
        internal static string str004 {
            get {
                return ResourceManager.GetString("str004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process files.
        /// </summary>
        internal static string str005 {
            get {
                return ResourceManager.GetString("str005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add source folder.
        /// </summary>
        internal static string str006 {
            get {
                return ResourceManager.GetString("str006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete source folder.
        /// </summary>
        internal static string str007 {
            get {
                return ResourceManager.GetString("str007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination folder.
        /// </summary>
        internal static string str008 {
            get {
                return ResourceManager.GetString("str008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process files.
        /// </summary>
        internal static string str009 {
            get {
                return ResourceManager.GetString("str009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string str010 {
            get {
                return ResourceManager.GetString("str010", resourceCulture);
            }
        }
    }
}
